name: Latest youtube activity
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsFTSQ6exutOIpP-wHl8qQQ"
          # Maximum number of posts you want
          max_post_count: "3"